# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth/auth.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'auth/auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x61uth/auth.proto\x12\x04\x61uth\"2\n\x0fRegisterRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"/\n\x0cLoginRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"=\n\x0c\x41uthResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\r\n\x05token\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"#\n\x12ValidateJWTRequest\x12\r\n\x05token\x18\x01 \x01(\t\"S\n\x13ValidateJWTResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\r\n\x05\x65rror\x18\x04 \x01(\t\"4\n\x13\x43reateApiKeyRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"S\n\x0e\x41piKeyResponse\x12\x0e\n\x06key_id\x18\x01 \x01(\t\x12\x0f\n\x07raw_key\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x12\n\ncreated_at\x18\x04 \x01(\t\"(\n\x15ValidateApiKeyRequest\x12\x0f\n\x07raw_key\x18\x01 \x01(\t\"W\n\x16ValidateApiKeyResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0e\n\x06key_id\x18\x03 \x01(\t\x12\r\n\x05\x65rror\x18\x04 \x01(\t\"6\n\x13RevokeApiKeyRequest\x12\x0e\n\x06key_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\"\'\n\x14RevokeApiKeyResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x8e\x03\n\x0b\x41uthService\x12\x35\n\x08Register\x12\x15.auth.RegisterRequest\x1a\x12.auth.AuthResponse\x12/\n\x05Login\x12\x12.auth.LoginRequest\x1a\x12.auth.AuthResponse\x12\x42\n\x0bValidateJWT\x12\x18.auth.ValidateJWTRequest\x1a\x19.auth.ValidateJWTResponse\x12?\n\x0c\x43reateApiKey\x12\x19.auth.CreateApiKeyRequest\x1a\x14.auth.ApiKeyResponse\x12K\n\x0eValidateApiKey\x12\x1b.auth.ValidateApiKeyRequest\x1a\x1c.auth.ValidateApiKeyResponse\x12\x45\n\x0cRevokeApiKey\x12\x19.auth.RevokeApiKeyRequest\x1a\x1a.auth.RevokeApiKeyResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth.auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERREQUEST']._serialized_start=25
  _globals['_REGISTERREQUEST']._serialized_end=75
  _globals['_LOGINREQUEST']._serialized_start=77
  _globals['_LOGINREQUEST']._serialized_end=124
  _globals['_AUTHRESPONSE']._serialized_start=126
  _globals['_AUTHRESPONSE']._serialized_end=187
  _globals['_VALIDATEJWTREQUEST']._serialized_start=189
  _globals['_VALIDATEJWTREQUEST']._serialized_end=224
  _globals['_VALIDATEJWTRESPONSE']._serialized_start=226
  _globals['_VALIDATEJWTRESPONSE']._serialized_end=309
  _globals['_CREATEAPIKEYREQUEST']._serialized_start=311
  _globals['_CREATEAPIKEYREQUEST']._serialized_end=363
  _globals['_APIKEYRESPONSE']._serialized_start=365
  _globals['_APIKEYRESPONSE']._serialized_end=448
  _globals['_VALIDATEAPIKEYREQUEST']._serialized_start=450
  _globals['_VALIDATEAPIKEYREQUEST']._serialized_end=490
  _globals['_VALIDATEAPIKEYRESPONSE']._serialized_start=492
  _globals['_VALIDATEAPIKEYRESPONSE']._serialized_end=579
  _globals['_REVOKEAPIKEYREQUEST']._serialized_start=581
  _globals['_REVOKEAPIKEYREQUEST']._serialized_end=635
  _globals['_REVOKEAPIKEYRESPONSE']._serialized_start=637
  _globals['_REVOKEAPIKEYRESPONSE']._serialized_end=676
  _globals['_AUTHSERVICE']._serialized_start=679
  _globals['_AUTHSERVICE']._serialized_end=1077
# @@protoc_insertion_point(module_scope)
