# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import ai_pb2 as ai_dot_ai__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ai/ai_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AIServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeIncident = channel.unary_unary(
                '/ai.AIService/AnalyzeIncident',
                request_serializer=ai_dot_ai__pb2.IncidentRequest.SerializeToString,
                response_deserializer=ai_dot_ai__pb2.AnalysisResult.FromString,
                _registered_method=True)
        self.ScanManifest = channel.unary_unary(
                '/ai.AIService/ScanManifest',
                request_serializer=ai_dot_ai__pb2.ManifestScanRequest.SerializeToString,
                response_deserializer=ai_dot_ai__pb2.ManifestScanResult.FromString,
                _registered_method=True)
        self.GetAnalysisHistory = channel.unary_unary(
                '/ai.AIService/GetAnalysisHistory',
                request_serializer=ai_dot_ai__pb2.HistoryRequest.SerializeToString,
                response_deserializer=ai_dot_ai__pb2.HistoryResponse.FromString,
                _registered_method=True)


class AIServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AnalyzeIncident(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ScanManifest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAnalysisHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeIncident': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeIncident,
                    request_deserializer=ai_dot_ai__pb2.IncidentRequest.FromString,
                    response_serializer=ai_dot_ai__pb2.AnalysisResult.SerializeToString,
            ),
            'ScanManifest': grpc.unary_unary_rpc_method_handler(
                    servicer.ScanManifest,
                    request_deserializer=ai_dot_ai__pb2.ManifestScanRequest.FromString,
                    response_serializer=ai_dot_ai__pb2.ManifestScanResult.SerializeToString,
            ),
            'GetAnalysisHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAnalysisHistory,
                    request_deserializer=ai_dot_ai__pb2.HistoryRequest.FromString,
                    response_serializer=ai_dot_ai__pb2.HistoryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai.AIService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai.AIService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AIService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AnalyzeIncident(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.AIService/AnalyzeIncident',
            ai_dot_ai__pb2.IncidentRequest.SerializeToString,
            ai_dot_ai__pb2.AnalysisResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ScanManifest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.AIService/ScanManifest',
            ai_dot_ai__pb2.ManifestScanRequest.SerializeToString,
            ai_dot_ai__pb2.ManifestScanResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAnalysisHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.AIService/GetAnalysisHistory',
            ai_dot_ai__pb2.HistoryRequest.SerializeToString,
            ai_dot_ai__pb2.HistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
