FROM grafana/grafana:11.3.1
COPY provisioning/datasources/datasources.yml /etc/grafana/provisioning/datasources/datasources.yml
COPY provisioning/dashboards/dashboards.yml   /etc/grafana/provisioning/dashboards/dashboards.yml
COPY provisioning/dashboards/podiq-overview.json /etc/grafana/provisioning/dashboards/podiq-overview.json
